-- TAO PROCEDURE
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='SP_DANGKYHOC')
BEGIN
	DROP PROCEDURE SP_DANGKYHOC
END
GO
CREATE PROCEDURE SP_DANGKYHOC
	@MAMON CHAR(5),
	@MASV CHAR(5),
	@KETQUA INT OUT
AS
BEGIN
-- KIEM TRA SINH VIEN DA DANG KY MON NAY HAY KHONG
	IF EXISTS (SELECT * FROM REGIST WHERE STUDENTID=@MASV 
				AND SUBJECTID=@MAMON)
		BEGIN
			SET @KETQUA=0
			PRINT 'SINH VIEN DA DANG KY MON NAY ROI'
		END
	ELSE	
		BEGIN
			DECLARE @DEM INT
--XEM SINH VIEN DA HOC BAO NHIEU MON
			SELECT @DEM=COUNT(*) FROM REGIST WHERE STUDENTID=@MASV
				GROUP BY STUDENTID
			IF @DEM>5
			BEGIN
				SET @KETQUA=0
				PRINT 'SINH VIEN NAY KHONG DUOC PHEP DANG KY HOC PHAN NAY'
			END
			ELSE
			BEGIN
				SET @KETQUA=1
				INSERT INTO REGIST(STUDENTID,SUBJECTID)
					VALUES(@MASV,@MAMON)
				PRINT 'DA DANG KY THANH CONG'
			END
		END
END

/*
DECLARE @KETQUA INT
EXEC SP_DANGKYHOC 20002,10001, @KETQUA OUT
SELECT @KETQUA

*/