DECLARE @BTT INT ,@BTT2 INT 
DECLARE @C CURSOR 
SET @C= CURSOR FOR SELECT MA_NVIEN,SODA FROM PHANCONG 

OPEN @C 
FETCH NEXT FROM @C INTO @BTT,@BTT2 

WHILE @@FETCH_STATUS =0 
BEGIN
FETCH NEXT FROM @C INTO @BTT,@BTT2
END
select @BTT,@BTT2