IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME ='TR_DELETE_DEAN')
BEGIN
	DROP TRIGGER TR_DELETE_DEAN
END
GO
CREATE TRIGGER TR_DELETE_DEAN ON DEAN
FOR DELETE
AS
BEGIN
	-- XU LY GIU LIEU TU TABLE DEAN
	DECLARE @MADA INT
	SELECT @MADA=MADA
	FROM DELETED
	--XOA GIU LIEU PHAN CONG
	DELETE FROM PHANCONG WHERE SODA=@MADA
END

