IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME ='TR_DELETE_NHANVIEN')
BEGIN
	DROP TRIGGER TR_DELETE_NHANVIEN
END
GO
CREATE TRIGGER TR_DELETE_NHANVIEN ON NHANVIEN
FOR DELETE
AS
BEGIN
	DECLARE @MANV BIGINT
	SELECT @MANV =MANV
	FROM DELETED
	-- PHANCONG
	DELETE FROM PHANCONG WHERE MA_NVIEN=@MANV
	-- THANNHAN
	DELETE FROM THANNHAN WHERE MA_NVIEN=@MANV
	IF EXISTS (SELECT * FROM PHONGBAN WHERE TRPHG=@MANV)
		BEGIN
			UPDATE PHONGBAN
			SET TRPHG=NULL WHERE TRPHG=@MANV
		END
	
END
