IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME ='TR_DEL_PHONGBAN')
BEGIN
	DROP TRIGGER TR_DEL_PHONGBAN
END
GO
CREATE TRIGGER TR_DEL_PHONGBAN ON PHONGBAN
FOR DELETE
AS
BEGIN
	--XU LY GIU LIEU CUA CAC TABLE LIEN QUANG
	DECLARE @MAPHG INT
	SELECT @MAPHG=MAPHG
	FROM DELETED 
	-- XOA GIU LIEU NHANVIEN
	DELETE FROM NHANVIEN WHERE PHG=@MAPHG
	DELETE FROM DIADIEM_PHG WHERE MAPHG=@MAPHG
END

