/*


•	Input : thong tin chi tiết cho 1 nhân viên
•	Output:  Status của chức năng (0 : insert, 1 : updated)
•	Process: Kiểm tra xem nhân viên này tồn tại chưa, nếu có rồi thì thong báo đã tồn tại và chuyển status =1 (update), đồng thời update thong tin của nhân viên đó lại. Nếu chưa có thì chuyển status = 0 (insert) và insert nhân viên đó vào trong database.

*/


IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='SP_CAPNHATNV')
BEGIN
	DROP PROCEDURE SP_CAPNHATNV
END
GO
CREATE PROCEDURE SP_CAPNHATNV
	@HONV NVARCHAR(15),@TENLOT NVARCHAR(15),@TENNV NVARCHAR(15),@MANV BIGINT ,@NGSINH DATETIME, @DCHI NVARCHAR(50),
	@PHAI NVARCHAR(10) ,@LUONG NUMERIC,
	@MA_NQL BIGINT,@PHG INT, @KETQUA VARCHAR(20) OUT
AS
BEGIN
	IF EXISTS (SELECT * FROM NHANVIEN WHERE MANV=@MANV)
	BEGIN
		SET @KETQUA='CUSSESS UPDATE  !'
		UPDATE NHANVIEN
		SET HONV=@HONV,TENLOT=@TENLOT,TENNV=@TENNV,NGSINH=@NGSINH,DCHI=@DCHI,PHAI=@PHAI,LUONG=@LUONG,
			MA_NQL=@MA_NQL,PHG=@PHG
		WHERE MANV=@MANV
		PRINT 'SUA THANH CONG'
	END
	ELSE
	BEGIN
		SET @KETQUA='CUSSESS INSERT  !'
		INSERT INTO NHANVIEN(HONV,TENLOT,TENNV,MANV,NGSINH,DCHI,PHAI,LUONG,MA_NQL,PHG)
		VALUES (@HONV,@TENLOT,@TENNV,@MANV,@NGSINH,@DCHI,@PHAI,@LUONG,@MA_NQL,@PHG)
		PRINT 'THEM THANH CONG'
	END
END

DECLARE @HIENTHI VARCHAR
EXEC SP_CAPNHATNV 'HUYNH','PHUNG','DUC',984111074,'11/28/1989','SO 1 DG 14 ','NAM',
	30000,'123456789',4, @HIENTHI OUT
SELECT @HIENTHI


SELECT * FROM NHANVIEN
