DROP PROCEDURE SP_THUNGHIEM
CREATE PROCEDURE SP_THUNGHIEM
	@TENDN NVARCHAR(15),@MATKHAU NVARCHAR(15), @KETQUA VARCHAR OUT
AS
BEGIN
	SELECT @KETQUA=COUNT(*)
	FROM THANHVIEN
	WHERE TENDN=@TENDN AND MATKHAU=@MATKHAU
	GROUP BY TENDN,MATKHAU
END


DECLARE @KQ VARCHAR
EXEC SP_THUNGHIEM 'TAIHK','TAIHK', @KQ OUT
SELECT @KQ AS 


