/*
3/ Phân công nhân viên theo đề án:
•	Input : MaDA,TenDA, DDiem_DA,MaPhg
•	Output:  
•	Process: 
o	Kiểm tra xem đề án này có tồn tại chưa, nếu chưa có thì sẽ insert dữ liệu vào trong table đề án, sau đó kiếm 3 nhân viên có số lượng phân công đề án ít nhất và tiến hành phân công cho đề án này. Sau đó thong báo ra kết quả như sau:
Đã phân công Đề án X cho nhân viên A thành công
Đã phân công Đề án X cho nhân viên B thành công
Đã phân công Đề án X cho nhân viên C thành công

o	Kiểm tra xem đề án này có tồn tại chưa, nếu có rồi thì đếm xem có bao 
nhiêu nhân viên đã tham gia đề án này rồi, nếu số lượng tham gia nhỏ hơn 5 thì sẽ phân công đề án này cho nhân viên có số đề án tham gia it nhất (nếu có từ 2 nhân viên trùng số đề án tham gia thì chọn nhân viên có tên theo thứ tự A-B), thong báo kết quả như sau:
Đã phân công Đề án X cho nhân viên Y thành công
*/

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME='SP_PHANCONGNV')
BEGIN
	DROP PROCEDURE SP_PHANCONGNV
END
GO
CREATE PROCEDURE SP_PHANCONGNV
	@MADA INT,@TENDA NVARCHAR(10),@DDIEM_DA NVARCHAR(10),@PHONG INT
AS
BEGIN
	
	-- KHAI BAO BIEN VA KIEM TRA DEAN
	DECLARE @DEM INT,@MANVIEN1 BIGINT,@MANVIEN2 BIGINT,
	@MANVIEN3 BIGINT, @MANVIEN4 BIGINT,@TENNV1 NVARCHAR(10),@TENNV2 NVARCHAR(10),
	@TENNV3 NVARCHAR(10),@TENNV4 NVARCHAR(10),@SOLUONG INT
	SELECT @DEM=COUNT(*) FROM DEAN WHERE TENDA=@TENDA AND MADA=@MADA AND DDIEM_DA=@DDIEM_DA AND PHONG=@PHONG
	IF @DEM=0
		BEGIN
			INSERT INTO DEAN(TENDA,MADA,DDIEM_DA,PHONG)
			VALUES (@TENDA,@MADA,@DDIEM_DA,@PHONG)
		END
	-- INSERT VAO PHANCONG
/*
	SELECT @MANVIEN1=B.MA_NVIEN,@TENNV1=A.TENNV FROM NHANVIEN AS A
	INNER JOIN PHANCONG AS B ON A.MANV=B.MA_NVIEN
	WHERE B.MA_NVIEN IN (SELECT TOP 3 MA_NVIEN FROM PHANCONG
									GROUP BY MA_NVIEN ORDER BY COUNT(SODA) ASC)
	
	SELECT @MANVIEN2=B.MA_NVIEN,@TENNV2=A.TENNV FROM NHANVIEN AS A
	INNER JOIN PHANCONG AS B ON A.MANV=B.MA_NVIEN
	WHERE  B.MA_NVIEN IN (SELECT TOP 3 MA_NVIEN FROM PHANCONG
									GROUP BY MA_NVIEN ORDER BY COUNT(SODA) ASC)
			AND B.MA_NVIEN<>@MANVIEN1 

	SELECT @MANVIEN3=B.MA_NVIEN,@TENNV3=A.TENNV FROM NHANVIEN AS A
	INNER JOIN PHANCONG AS B ON A.MANV=B.MA_NVIEN
	WHERE  B.MA_NVIEN IN (SELECT TOP 3 MA_NVIEN FROM PHANCONG
									GROUP BY MA_NVIEN ORDER BY COUNT(SODA) ASC)
			AND B.MA_NVIEN<>@MANVIEN2 AND B.MA_NVIEN<>@MANVIEN1
	
	INSERT INTO PHANCONG (MA_NVIEN,SODA,THOIGIAN)
			VALUES(@MANVIEN1,@MADA,'')

	
	PRINT 'DA PHAN CONG DE AN '+@TENDA+' CHO NHAN VIEN '+@TENNV1+' THANH CONG'

	INSERT INTO PHANCONG (MA_NVIEN,SODA,THOIGIAN)
			VALUES(@MANVIEN2,@MADA,'')

	PRINT 'DA PHAN CONG DE AN'+@TENDA+'CHO NHAN VIEN '+@TENNV2+' THANH CONG'	

	INSERT INTO PHANCONG (MA_NVIEN,SODA,THOIGIAN)
			VALUES(@MANVIEN3,@MADA,'')
	PRINT 'DA PHAN CONG DE AN '+@TENDA+' CHO NHAN VIEN '+@TENNV3+' THANH CONG'
	SET @KETQUA=1
*/

		DECLARE @MANV BIGINT,
				@TENNV VARCHAR(10)
		DECLARE @C CURSOR 
		SET @C = CURSOR FOR SELECT TOP 3 A.MA_NVIEN,B.TENNV FROM PHANCONG AS A
												INNER JOIN NHANVIEN AS B ON A.MA_NVIEN=B.MANV
												 GROUP BY A.MA_NVIEN,B.TENNV ORDER BY COUNT(A.SODA) ASC, B.TENNV
		OPEN @C
		FETCH NEXT FROM @C INTO @MANV,@TENNV
		WHILE @@FETCH_STATUS=0
		BEGIN
			INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
					VALUES (@MANV,@MADA,NULL)

			FETCH NEXT FROM @C INTO @MANV,@TENNV
			PRINT 'DA PHAN CONG DE AN '+@TENDA+'CHO NHAN VIEN '+@TENNV+'THANH CONG'
		END
	CLOSE @C
	DEALLOCATE @C;

	IF EXISTS (SELECT * FROM DEAN WHERE TENDA=@TENDA AND MADA=@MADA)
		BEGIN
			SELECT @SOLUONG=COUNT(*) FROM PHANCONG WHERE SODA=@MADA
			IF @SOLUONG <5
				BEGIN
					SELECT	@TENNV4=A.TENNV,
							@MANVIEN4=B.MA_NVIEN
					FROM NHANVIEN AS A
					INNER JOIN PHANCONG AS B ON A.MANV=B.MA_NVIEN
					WHERE  B.MA_NVIEN IN (SELECT TOP 1  MA_NVIEN FROM PHANCONG
									WHERE MA_NVIEN <>@MANVIEN1 AND MA_NVIEN <>@MANVIEN2 AND MA_NVIEN <>@MANVIEN3
									GROUP BY MA_NVIEN ORDER BY COUNT(SODA) ASC)
					INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
						VALUES (@MANVIEN4,@MADA,'')
					PRINT 'DA PHAN CONG DE AN '+ @TENDA +'CHO NHAN VIEN '+ @TENNV4 +' THANH CONG'
				END
			
		END
END





/*
DECLARE @THUNGHIEM INT 
EXEC SP_PHANCONGNV 7,'THUNGHIEM','KIEN GIANG',2
SELECT @THUNGHIEM

SELECT * FROM DEAN

*/