IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE NAME ='TR_INSERT_DEAN')
BEGIN
	DROP TRIGGER TR_INSERT_DEAN
END
GO
CREATE TRIGGER TR_INSERT_DEAN ON DEAN
FOR INSERT
AS
BEGIN
	DECLARE @MANV BIGINT
	DECLARE @MADA INT, @PHONG INT
	SELECT @MADA=MADA,@PHONG=PHONG
	FROM INSERTED
	-- CHEN GIU LIEU PHANCONG
	SELECT @MANV=MANV
	FROM NHANVIEN
	WHERE PHG=@PHONG
	IF @MANV>0
	BEGIN
		INSERT INTO PHANCONG(MA_NVIEN,SODA,THOIGIAN)
		VALUES (@MANV,@MADA,NULL)
	END
	ELSE
	BEGIN
		PRINT 'PHONG BAN CO MA = '+CAST (@PHONG AS VARCHAR)+' HIEN TAI CHUA CO NHAN VIEN'
	END
/*
	DECLARE @C CURSOR
	SET @C = CURSOR FOR 
	SELECT TOP 3 @MANV=MA_NVIEN
	FROM PHANCONG GROUP BY MA_NVIEN ORDER BY COUNT(SODA) ASC
	OPEN @C
	FETCH NEXT @C INTO @MANV
	WHILE @@FETCH_STATUS=0
	BEGIN
		INSERT INTO PHANCONG(MANV,SODA,THOIGIAN)
		VALUES (@MANV,@MADA,NULL)
		FETCH NEXT @C INTO @MANV
	END
	CLOSE @C
	DEALLOCATE @C
*/
END