CREATE VIEW V_NHANVIEN
AS
SELECT A.MANV, A.HONV+' '+A.TENLOT+' '+A.TENNV AS 'HOTENNV' , A.DCHI , B.SODA, B.THOIGIAN
FROM NHANVIEN AS A 
INNER JOIN PHANCONG AS B ON A.MANV = B.MA_NVIEN

DROP VIEW V_NHANVIEN
SELECT * FROM V_NHANVIEN

CREATE VIEW V_THONGTINH_NHANVIEN
AS
SELECT B.MANV, B.HOTENNV, B.DCHI,A.PHAI,A.LUONG , B.SODA, B.THOIGIAN
FROM NHANVIEN AS A
INNER JOIN V_NHANVIEN AS B ON A.MANV=B.MANV

DROP VIEW V_THONGTINH_NHANVIEN

SELECT * FROM V_THONGTINH_NHANVIEN