CREATE PROC SP_TIMKIEMNHANVIENTHEODEAN
	@MADEAN INT
AS 
BEGIN
	IF EXISTS (SELECT * FROM DEAN WHERE MADA = @MADEAN)
	BEGIN
		SELECT A.HONV + ' '+ A.TENLOT + ' '+ A.TENNV AS HOTEN,A.MANV
		FROM NHANVIEN AS A 
		INNER JOIN PHANCONG AS B ON A.MANV = B.MA_NVIEN
		
	END
END
	